### ISSUE TITLE
Allow customizing McDev bannedClasses

### ISSUE THREAD

**Issue by notOM3GA** [PaperMC/paperweight#10]
This would be useful for forks that add files to nms.

**Comment by jpenilla** [comment]
"bannedClasses" is a temporary workaround until Paper's patches have all been updated, after which all Paper-added classes in minecraft packages will be moved into paper packages. The hard fail for missing classes has been removed, so forks should be able to update as well, but I recommend just moving your classes into your own packages.

**Comment by notOM3GA** [comment]
oh ok
