### ISSUE TITLE
Gradle multimodule build will use the -dev jar

### ISSUE THREAD

**Issue by NeumimTo** [PaperMC/paperweight#105]
Assume multimodule environment where A is a module that is the final plugin .jar and B is module that has nms on classpath

A 
```
dependencies {
   api(project(":B"))
}
```

B
```
dependencies {
   paperDevBundle(...)
}


build {
  dependsOn(reobfJar)
}
```

Task B produces multiple jars
B-sources.jar
B-dev.jar (no reobf)
B.jar (reobf)

In the A jar will exploded B-dev.jar instead B.jar

tested on 1.1.12 and 14

**Comment by jpenilla** [comment]
This use case requires depending on the reobf configuration. `api(project(":B", "reobf"))`
