### ISSUE TITLE
./gradlew paperclipJar throws exceptions for forks

### ISSUE THREAD

**Issue by yannicklamprecht** [PaperMC/paperweight#114]
When running ./gradlew paperclipJar the generateReobfMappings task called by paperclipJar logs the following FAILURE.

```
* What went wrong:
A problem was found with the configuration of task ':generateReobfMappings' (type 'GenerateReobfMappings').
  - In plugin 'io.papermc.paperweight.patcher' type 'io.papermc.paperweight.tasks.GenerateReobfMappings' property 'spigotRecompiledClasses' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'spigotRecompiledClasses'.
      2. Mark property 'spigotRecompiledClasses' as optional.
```

Paperweight version 1.2.0

Steps to reproduce:

1. `./gradlew applyPatches`
2. `./gradlew paperclipJar`

**Comment by jpenilla** [comment]
Is your upstream also using paperweight 1.2.0?
https://github.com/PaperMC/paperweight/blob/7de5af8681c36a4e32713cb5f37e4d83fd2552b6/paperweight-patcher/src/main/kotlin/PaperweightPatcher.kt#L163
The value is configured from upstream data here.

**Comment by yannicklamprecht** [comment]
Thank's for pointing it out. I was one upstream commit before 1.2.0 was added.
