### ISSUE TITLE
Question: Paperweight renewal policy

### ISSUE THREAD

**Issue by Dymeth** [PaperMC/paperweight#115]
Hello.

In connection with the upcoming 1.18 update, I have a question about the paperweight update policy.

After the release of MC 1.18, a new version of the paperweight will be released after some time, which will bring a new version of the mappings. Will we still be able to use paperDevBundle 1.17 for some time?

If it does, are you planning to disable this version in the long term? For example, after the release of 1.19.

**Comment by jpenilla** [comment]
I'm not sure what the question is? 1.17.1 will continue to use 1.2.0, and you are free to continue using 1.2.0 and the 1.17.1 dev bundle.

**Comment by Dymeth** [comment]
> I'm not sure I understand what the question is? 1.17.1 will continue to use 1.2.0, and you are free to continue using 1.2.0 and the 1.17.1 dev bundle.

After the release of a new version of paperweigth, the use of older versions is no longer possible. Paperweigth forces developers to always use the latest version.
Thus, after the release of paperweigth for 1.18, developers will be required to start using the new version of paperweigth

**Comment by jpenilla** [comment]
> Paperweigth forces developers to always use the latest version.

No, it doesn't? I think there may be a misunderstanding here.

**Comment by Dymeth** [comment]
> > Paperweigth forces developers to always use the latest version.
> 
> No, it doesn't? I think there may be a misunderstanding here.

In this case, it may be due to some technical problem.
Currently my project is using paperweright 1.2.0.
When trying to rollback a version to 1.1.12, I get this error:
`The paperweight development bundle you are attempting to use is of data version '2', but the currently running version of paperweight only supports data version '1'.`

But with versions 1.1.13 and 1.1.14, I do not see this problem. Maybe this behavior is related to some problem that was fixed earlier?

**Comment by jpenilla** [comment]
You are depending on the dev bundle using a snapshot... You need to depend on a version of the dev bundle built using the version of paperweight you are trying to use.
