### ISSUE TITLE
Bug with setting color

### ISSUE THREAD

**Issue by josephjthomas** [PaperMC/paperweight#117]
I can't set up paperweight userdev in my project. It fails with
```
diff: unrecognized option `--color=never'
diff: Try `diff --help' for more information.
```
paperDevBundle version 1.18-rc3-R0.1-SNAPSHOT, gnu diffutils 3.8

**Comment by sulu5890** [comment]
GNU diff is currently required. If you're on a Mac, where this is not defaulted, install coreutils via homebrew. Else you should be able to figure it out.

**Comment by josephjthomas** [comment]
My output of diff -v:
```
$ diff -v
diff (GNU diffutils) 3.8
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Paul Eggert, Mike Haertel, David Hayes,
Richard Stallman, and Len Tower.
```
I have the correct version.

**Comment by electronicboy** [comment]
if this is not a dev bundle that you created yourself, you may nee to tell it to update as there was issues with the OG deployment of it

**Comment by josephjthomas** [comment]
I cleared my cache and apparently now have the up to date version, thanks.
But I can't apply it on my project. I always get
```
error: patch failed: blockscore/.gradle/caches/paperweight/setupCache/patchedSourcesJar.jar-2136113101/net/minecraft/world/level/LevelAccessor.java:18
patch failed: blockscore/.gradle/caches/paperweight/setupCache/patchedSourcesJar.jar-2136113101/net/minecraft/world/level/LevelAccessor.java:18
```
What's up with that patch?

**Comment by josephjthomas** [comment]
Here is the stracktrace it generates if that helps you https://paste.gg/p/anonymous/3f01b2525f40499fb149ad25cef20bb1
