### ISSUE TITLE
Failed to apply patch.

### ISSUE THREAD

**Issue by norhu1130** [PaperMC/paperweight#119]
> Task :paper:patchCraftBukkitPatches FAILED
error: patch failed: .gradle/caches/paperweight/taskCache/patchCraftBukkitPatches.zip--401417275/net/minecraft/world/entity/ai/behavior/BehaviorWorkComposter.patch:1
error: .gradle/caches/paperweight/taskCache/patchCraftBukkitPatches.zip--401417275/net/minecraft/world/entity/ai/behavior/BehaviorWorkComposter.patch: patch does not apply

> Task :getPaperUpstreamData FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':paper:patchCraftBukkitPatches'.
> io.papermc.paperweight.PaperweightException: Command finished with 1 exit code: git -c commit.gpgsign=false -c core.safecrlf=false apply D:\Airplane\.gradle\caches\paperweight\upstreams\paper\build-data\craftbukkit-patch-patches\BehaviorWorkComposter.patch.patch

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 17s
2 actionable tasks: 2 executed

Why is this like this?

**Comment by yannicklamprecht** [comment]
The deployed dev bundle has problems.
You need to generate your own dev bundle locally.

clone paper, checkout the dev/1.18 branch and and 
`gradle publishToMavenLocal -PpublishDevBundle`

Then add mavenLocal() to your repositories in build.gradle(.kts)

**Comment by norhu1130** [comment]
I think I did something wrong, but there's an error.
https://pastebin.com/Xd7xCvRY

**Comment by aurorasmiles** [comment]
You need to use `./gradlew applyPatches` first

**Comment by norhu1130** [comment]
I'm such a fool

**Comment by norhu1130** [comment]
https://pastebin.com/5mEFKsVpA 
similar error occurs before.
Can you tell me how to proceed in detail?

**Comment by norhu1130** [comment]
? Why does it work well in a Ubuntu environment?

**Comment by MiniDigger** [comment]
your paste is deleted

**Comment by Logics4** [comment]
> The deployed dev bundle has problems.
> You need to generate your own dev bundle locally.
> 
> clone paper, checkout the dev/1.18 branch and run
> `./gradlew publishToMavenLocal -PpublishDevBundle`
> 
> Then add mavenLocal() to your repositories in build.gradle(.kts)
> 
> Delete .gradle to be sure it extract freshly.
> 
> Side note: you need gnu diff.

I'm trying to use the paperweight-examples repository, which I'm assuming it's for 1.17.1. I tried cloning Paper and running `./gradlew publishToMavenLocal -PpublishDevBundle` on it but it did not work:
```gradle
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':generateDevelopmentBundle'.
> Extension of type 'RelocationExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, BasePluginExtension, DefaultArtifactPublicationSet, SourceSetContainer, ReportingExtension, JavaPluginExtension, JavaToolchainService, TestingExtension, PublishingExtension, ShadowExtension]
```
I can't use `applyPatches` first because it gives me the exact error as the first post.
Is the offending patch of any importance? Could I just remove it if it's getting in my way? Or is there any other way to fix this? I'm not sure why the issue was closed.
