### ISSUE TITLE
Bundler jar libraries include API twice

### ISSUE THREAD

**Issue by theomega24** [PaperMC/paperweight#124]
The bundler jar libraries seem to include Paper-API and the forks API, which means that none of the forks API is included in the final product.

This means that I end up running Purpur-Server with Paper-API, which causes issues. https://pastebin.com/MPJtyqJM ([api patch](https://github.com/PurpurMC/Purpur/blob/9beb23b8c388c3c00357f74f22d4d1d9044bfe50/patches/api/0007-Allow-inventory-resizing.patch)).

**Comment by theomega24** [comment]
Oh and here is a jar that causes the issue: https://drive.google.com/file/d/1cMCuPISYiZY8qlSroW-dmNvZtKnP9zFs/view?usp=sharing

**Comment by lynxplay** [comment]
The `paper-mojangapi` artifact ist transitively depending on the `paper-api` and hence it is included in the bundler.
You can exclude the transitive dependency (as the fork's api delivers the classes needed) through something like 
```kt
implementation("io.papermc.paper:paper-mojangapi:1.18-R0.1-SNAPSHOT") { 
    exclude("io.papermc.paper", "paper-api") 
}
```
I expect this to be the solution, however this could obviously also be implemented as a check somewhere in the patcher, so this issue might need more input.

**Comment by theomega24** [comment]
This is probably the case, I’ll definitely try this when I get home. Thanks!

**Comment by lynxplay** [comment]
Yea I validated this on a local fork, the `paper-api` is no longer included in the bundler after excluding it from the `mojangapi` :+1:
I'll close the issue for now, if problems arise feel free to comment and we can re-open and discuss further :)
