### ISSUE TITLE
Paperweight with maven

### ISSUE THREAD

**Issue by konstantinosmelis** [PaperMC/paperweight#133]
# What is the problem?
After running `mvn clean install` in my maven project trying to include paperweight I found myself with an error that after researching in the paper's maven repo is accurate.

# How to reproduce it?
After cloning the paperweight git repo and executing the command `./gradlew publishToMavenLocal`, add the following lines to your maven project:
```
<repositories>
    <repository>
        id>papermc-repo</id>
        url>https://papermc.io/repo/repository/maven-public/</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>io.papermc.paperweight</groupId>
        <artifactId>paperweight-userdev</artifactId>
        <version>1.3.4-LOCAL-SNAPSHOT</version>
        <scope>provided</scope>
    </dependency>
</dependencies>
```

# Expected result
Paperweight shoul be installed in the maven project.

# Actual result
The error message is the following:
`Failure to find io.papermc.paperweight:paperweight-lib:jar:1.3.4-SNAPSHOT in https://papermc.io/repo/repository/maven-public/`

**Comment by electronicboy** [comment]
paperweight lib is not published to a repo as it's included at runtime already into the jar, you'd need to manually exclude that artefact
