### ISSUE TITLE
Parchment support

### ISSUE THREAD

**Issue by Titaniumtown** [PaperMC/paperweight#136]
[Parchment](https://github.com/ParchmentMC/Parchment) is a project that provides "Open community-sourced parameter names and javadocs" on top of Mojang's mappings. This would be really nice to have in paperweight. I don't know if this has been discussed before, so that's why I'm opening this issue.

**Comment by Elierrr** [comment]
Paperweight already supports custom parameter names but it only supports tiny mappings and most likely won’t add support for Parchment mappings. An alternative is to create a parser to convert their mappings to tiny. Also adding support for javadoc mappings is a good idea that should be implemented in my opinion.

**Comment by electronicboy** [comment]
There was internal talks about this time ago, I believe that there was some concerns in regards to its maturity as well as the potential noise it would introduce in the meantime, etc

**Comment by jpenilla** [comment]
Parchment support only makes sense to add into paperweight if Paper decides to start using parchment. Actually implementing it would be trivial. Therefore this isn't the right place for this issue.
