### ISSUE TITLE
Running task GenerateDevBundle on Windows system is impossible.

### ISSUE THREAD

**Issue by rgnter** [PaperMC/paperweight#142]
https://github.com/PaperMC/paperweight/blob/94962163a6ca3f2a4e9188120e3c6b79aa9123c1/paperweight-lib/src/main/kotlin/tasks/GenerateDevBundle.kt#L270

This command, does not work on Windows platform unless third-party software is installed.
Either add this to prerequisites or find a way to use a different command.

**Comment by jpenilla** [comment]
https://github.com/PaperMC/paperweight/issues/65
