### ISSUE TITLE
class not found, but mapping is shaded 

### ISSUE THREAD

**Issue by CrazyL3gend** [PaperMC/paperweight#144]
Hello. I have a problem with enable plugin with mojang mapping, I shade in plugin mojang mappings and in jar I see net/minecraft/world/entity/monster/Zombie, but plugin give me this error java.lang.NoClassDefFoundError: net/minecraft/world/entity/monster/Zombie, I am also have kotlin and kotlin dsl. 
![изображение](https://user-images.githubusercontent.com/63064550/159092552-cb52d36e-422c-456c-bb42-260bec736b2c.png)
![изображение](https://user-images.githubusercontent.com/63064550/159092572-6d639506-6a9c-4fa4-aecb-adef3fc92212.png)
![изображение](https://user-images.githubusercontent.com/63064550/159092616-0f58c82c-e2ae-49dc-881b-a51efe2f249a.png)

**Comment by MiniDigger** [comment]
you need to run the reobf jar, as the server doesn't use mojang mappings at runtime (yet...)

**Comment by ComputerNerd100** [comment]
+1 on MiniDigger's comment. Mojang-mapped JARs are currently development-only.
Assuming you're using gradle + userdev:
```
tasks {
    assemble {
        dependsOn(reobfJar)
    }
}
```
Adding this to your build.gradle.kts will ensure gradle calls the reobfJar task from userdev before building your JAR :)

**Comment by CrazyL3gend** [comment]
now I have another problem, I have this fatJar task gradle
![изображение](https://user-images.githubusercontent.com/63064550/159129625-b6f4ab60-7fb2-4d5d-beba-d76f7bb41c4c.png)

reobfJar working but I have same error with classNotFound
![изображение](https://user-images.githubusercontent.com/63064550/159129647-e068e8b5-3824-4c40-99ff-8f2c18ac7699.png)

**Comment by sulu5890** [comment]
Please ask on our [discord](https://discord.gg/papermc) or forums for future support with this. This is not a paperweight issue, and the issue tracker is not the best place for help.
