### ISSUE TITLE
Cannot import com.mojang.math classes

### ISSUE THREAD

**Issue by etil2jz** [PaperMC/paperweight#146]
The `com.mojang.math` package is part of the minecraft source, not other library.
Paperweight currently expects any import from the minecraft namespace to exist in `net/minecraft`, making i.e. `minecraft com.mojang.math.OctahedralGroup` or `minecraft com.mojang.math.Transformation` impossible.

**Comment by lynxplay** [comment]
See https://github.com/PaperMC/paperweight/blob/49031b3f19712a0790debbdf1b43814a6efdd086/paperweight-lib/src/main/kotlin/util/McDev.kt#L51 and the general [readMcDevNames](https://github.com/PaperMC/paperweight/blob/main/paperweight-lib/src/main/kotlin/util/McDev.kt#L137) method.
