### ISSUE TITLE
applyPatches on a fork of a fork fails with java.util.zip.ZipException: invalid code lengths set

### ISSUE THREAD

**Issue by Malfrador** [PaperMC/paperweight#149]
When trying to use applyPatches to build a fork of a fork (Pufferfish in this case), paperweight fails with a `java.util.zip.ZipException: invalid code lengths set`.

My build.gradle.kts: https://pastes.dev/r8nL5VhW6X
Full log with ` --info --stacktrace`: https://pastes.dev/zJxfUUBTSb
Running gradle with `--debug` was not possible due to gradle running out of memory (even though I gave it 16 GB using `org.gradle.jvmargs=` in `gradle.properties`

Gradle is running in WSL2 with openjdk 17.0.2. McDevImports.txt is empty and there are no patches currently. 
Building Paper itself in the same environment works fine, as does building a direct fork of paper

The .zip and .jar files in `.gradle\caches\paperweight\upstreams\paper\.gradle\caches\paperweight\taskCache` seem to be valid according to 7zips "Test zip file" feature.

**Comment by AlexisBG06** [comment]
I have this issue too.

**Comment by jpenilla** [comment]
The pastes are expired, but I have an idea of what was likely happening here, and there are safeguards against it in v2. Please open a new issue if this happens in v2.
