### ISSUE TITLE
Wrong Remapping name

### ISSUE THREAD

**Issue by mcsim415** [PaperMC/paperweight#152]
`import net.minecraft.nbt.ListTag`
and
`logger.info(StringTag::class.simpleName)`
but it says `NBTTagString`
It's my first time using something like this, so I have no idea.
How can I rename it properly?

**Comment by kennytv** [comment]
The reobfuscated server uses Spigot class names at runtime. If you have any specific questions, you can use the paper-dev channel on our Discord
