### ISSUE TITLE
Support for separate API and server upstream data

### ISSUE THREAD

**Issue by mastercoms** [PaperMC/paperweight#153]
Currently, upstream data is prepared for both API and server, which causes an upstream to prepare unnecessary outputs in its prepare for downstream task, if the downstream only uses the API (like Glowstone's [Glowkit](https://github.com/GlowstoneMC/Glowkit)).

Downstream should be able to specify that it does not need certain outputs from upstream.

**Comment by jpenilla** [comment]
This will be possible in patcher v2
