### ISSUE TITLE
Failed to apply patch in ubuntu

### ISSUE THREAD

**Issue by Crolikoved1533** [PaperMC/paperweight#156]
./gradlew applyPatches
<-------------> 5% EXECUTING [1m 8s]
<-------------> 5% EXECUTING [1m 10s]
<-------------> 5% EXECUTING [1m 13s]

> Task :patchSpigotApi

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <sory@DESKTOP-GCQ143U.localdomain>) not allowed
***   Please review above details and finish the apply then
***   save the changes with `./gradlew rebuildPatches`

> Task :patchSpigotApi FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':patchSpigotApi'.
> io.papermc.paperweight.PaperweightException: Failed to apply patches

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 34s
3 actionable tasks: 2 executed, 1 up-to-date

**Comment by electronicboy** [comment]
You need to set the git user/email, the auto defaults for that failed to create something valid
