### ISSUE TITLE
spigotDecomplieJar error

### ISSUE THREAD

**Issue by s-yh-china** [PaperMC/paperweight#158]
In task spigotDecomplieJar, if your computer has less phy memory(like 4G), task will error with java heap dump.

In linux task will print out error, but in windows it will run forever

The task run command without -Xmx to set MaxHeapSize so jvm will use def value (1/4 of phy memory).

**Comment by MiniDigger** [comment]
the task actually needs an increased amount of RAM to complete. giving it 1gb like you are suggesting wouldn't be enough.
what kinda device are you trying to run paperweight on and why?
