### ISSUE TITLE
Special Identifier for reobf tasks

### ISSUE THREAD

**Issue by IBims1ckoky** [PaperMC/paperweight#159]
I think its better if the compiled plugin jar (from the reobf task) have a special identifier as filename ending (like -reobf).

**Comment by jpenilla** [comment]
I don't agree, also I don't think changing this outside of a major revision (which isn't planned) is good ux. The production artifact having no classifier is a good and intuitive default for new users, which is also done on fabric and other modding platforms. If this isn't good for your application, you can of course change things yourself.
