### ISSUE TITLE
Command finished with 128 exit code: git -c commit.gpgsign=false -c core.safecrlf=false submodule update --init

### ISSUE THREAD

**Issue by Nishh** [PaperMC/paperweight#160]
Trying to build paper
gradlew applyPatches
gives this error:
https://pastebin.com/EqFYAYQj

JDK version: 17

Tried setting JAVA_HOME to JDK-17
Tried full cleanup

Not sure if I should create an issue in papermc or paperweight github page.

**Comment by electronicboy** [comment]
> fatal: not a git repository (or any of the parent directories): .git

You need to clone the repo, not use the zip download thing

**Comment by Nishh** [comment]
Sorry, just learned downloading a repo and cloning it are not the same thing.
