### ISSUE TITLE
Question regrading weird behavior if intended or not

### ISSUE THREAD

**Issue by ham1255** [PaperMC/paperweight#162]
not sure if this right place to ask questions but,
got question regarding paperweight-patcher for some reason 
`generateDevBundle` jar is ignoring subproject like this `implementation(project(:SubProject))`,  which when inspecting `config.json` of the dev bundle jar its no were to be found in compile / runtime dependencies, is this normal behavior? if yes how i can include it? 

*this same question i asked on discord guild but got no reply*

**Comment by jpenilla** [comment]
project dependencies are support in the dev bundle with paperweight v2
