### ISSUE TITLE
Rename jar files?

### ISSUE THREAD

**Issue by dkim19375** [PaperMC/paperweight#164]
How do I rename all of the outputs?
I have:
```kotlin
tasks {
    reobfJar {
        outputJar.set(File(buildDir, "libs/NewName-$version.jar"))
    }
    shadowJar {
        archiveBaseName.set("NewName")
        archiveClassifier.set("")
    }
}
```
but the files in `build/libs` when doing `gradle clean reobfJar` are:
```
NewName-1.0.0.jar
NewName-1.0.0-dev-all.jar
OldName-1.0.0-dev.jar
```
A workaround is to manually rename, but is there a way to rename automatically?

**Comment by jpenilla** [comment]
This is really more a gradle help question than a paperweight issue, but you want to set the archives base name on the BaseExtension `base.archivesBaseName.set("BaseName")`
