### ISSUE TITLE
Newly added overriding methods with covariant return types are not remapped during reobf

### ISSUE THREAD

**Issue by syldium** [PaperMC/paperweight#17]
When a method override another with a subclass return type, the output of *reobfJar* is incorrect.

Example (Spigot names):
There is a `#getChunkAt(int, int)` method in the *World* class that returns a *Chunk*, which overrides a method in the  *IBlockAccess* interface (returns an *IChunkAccess*). In the remapped .jar, the `World#getChunkAt` method refers to the interface method, and a new method is added in the *World* class, `#getChunk(int, int)`, the non-remapped method.

Testing code: https://paste.gg/p/syldium/fe11735592144369b594e5cae3f60a4c

**Comment by DenWav** [comment]
I had hoped `tiny-remapper` would handle these cases but it seems it doesn't. Fix for this is to run Hypo over the reobf mappings during `generateReobfMappings`.
