### ISSUE TITLE
[Question] Multi-module cache UserDev

### ISSUE THREAD

**Issue by devwckd** [PaperMC/paperweight#175]
Hi, I'm using `io.papermc.paperweight.userdev` on different modules on a mono-repo and I noticed that the cache is contained on the submodule, like the following:
![image](https://user-images.githubusercontent.com/65056371/209419075-aaaf4a9d-e146-4e36-848f-a4537e23cb68.png)

It's re-building devBundle for each project even though I use the same version on all of them, is there a way I can specify a common cache folder for all of them so it doesn't run more than once?

Thanks :D

**Comment by luiz-otavio** [comment]
Same here. I would like something like this to reduce my time to setup all gradle tasks in my IDE as it takes a lot of time to read and make mapping of the minecraft-server itself.

**Comment by jpenilla** [comment]
If multiple projects in a build depend on the same dev bundle they will share caches, this has been the case for quite a while (699b8499510dffb66454bc59533676564c4840f8). We need more details about your setup beyond a screenshot of cache directories. If you aren't able to isolate what's causing the issue or share your repo, creating a minimal reproducer is probably the best way to diagnose this.

Also, keep in mind if you were adding paperweight to one subproject at a time in the process of setting up your build, caches may be left behind that aren't actually used any more, which could look misleading.

**Comment by devwckd** [comment]
> If multiple projects in a build depend on the same dev bundle they will share caches, this has been the case for quite a while ([699b849](https://github.com/PaperMC/paperweight/commit/699b8499510dffb66454bc59533676564c4840f8)). We need more details about your setup beyond a screenshot of cache directories. If you aren't able to isolate what's causing the issue or share your repo, creating a minimal reproducer is probably the best way to diagnose this.
> 
> Also, keep in mind if you were adding paperweight to one subproject at a time in the process of setting up your build, caches may be left behind that aren't actually used any more, which could look misleading.

Got it, I deleted all .gradle and build folders and rebuillt the project and it only created on .gradle, seems like its working, thanks for the help :D
