### ISSUE TITLE
consumableRuntimeClasspath not resolved after update to 1.5

### ISSUE THREAD

**Issue by FriwiDev** [PaperMC/paperweight#188]
We use our own paper fork to expose some custom api. Sadly with the newest paper revisions, we run into an error when using the patcher plugin (v.1.5.2/3) while executing the `createReobfBundlerJar` task:

`Project : declares a dependency from configuration 'serverRuntimeClasspath' to configuration 'consumableRuntimeClasspath' which is not declared in the descriptor for project :`

We have not changed anything about our code base. Do you know what could cause this issue now as a change from 1.4.1 to 1.5.3?

**Comment by jpenilla** [comment]
`#build-tooling-help` on the Paper discord would be a better place to try and troubleshoot this. To start, create a build scan (invoke the task like normal but add `--scan` at the end), open the link and activate the scan, then send the link in `#build-tooling-help`, along with ideally a link to your repo (but pastes of your scripts is *fine* if it's private).  If we determine there is actually a paperweight issue, we can reopen this with more details.

**Comment by FriwiDev** [comment]
Alright, I posted a scan in the channel :)

**Comment by FriwiDev** [comment]
The underlying issue was that the root project had the same name as a child project, resulting in ambiguous paths. Thanks to jpenilla for resolving this issue :)
