### ISSUE TITLE
Allow access transformers for forks

### ISSUE THREAD

**Issue by yannicklamprecht** [PaperMC/paperweight#193]
Seems like the issue got lost [here](https://github.com/PaperMC/paperweight-examples/issues/4).
Too keep better track of it I'll open it here.

**Request:**

Add a possibility to declare AT's in forks of paper.

**Comment by TheShermanTanker** [comment]
Sorry I haven't had time to work on the enhancement for quite a while, I will try to return to paperweight development soon

**Comment by MiniDigger** [comment]
I wrote a thing that can apply ATs to source (pending cleanup): https://github.com/PaperMC/paperweight/blob/softspoon-v2/paperweight-lib/src/main/kotlin/io/papermc/paperweight/tasks/softspoon/ApplySourceAT.kt

if there is interest, that can be ported by somebody and used for fork ATs

**Comment by jpenilla** [comment]
Will be implemented in v2, at first only for MC sources but later for all patched sources.
