### ISSUE TITLE
BlockState to IBlockData

### ISSUE THREAD

**Issue by StanByes** [PaperMC/paperweight#201]
Hello, I tried to use the net.minecraft.world.level.block.state.BlockState in my plugin to get Internal ID of a block.
After use the reobfJar task, I've launched my plugin and I got this error : 
`Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.level.block.state.BlockState org.bukkit.craftbukkit.v1_19_R3.block.data.CraftBlockData.getState()'`
After a look in https://mappings.cephx.dev/1.19.4 page, I saw that the class should be rename to IBlockData but when I decompiled the class of my plugin, the reobfJar task has let BlockState name.
I don't know if is an error with paperweight or not so I put it here !
Thank's
```[tasklist]
### Tasks
```

**Comment by StanByes** [comment]
I forgot : 
- Paperweight version : 1.5.5
- Dev bundle : io.papermc.paper:dev-bundle:1.19.4-R0.1-SNAPSHOT

**Comment by jpenilla** [comment]
That method remaps fine: 
![Screenshot 2023-07-12 at 5 19 22 PM](https://github.com/PaperMC/paperweight/assets/11360596/992e8938-c5ea-4fa9-93eb-d4174f902481)
![Screenshot 2023-07-12 at 5 18 40 PM](https://github.com/PaperMC/paperweight/assets/11360596/4b7ef35a-5343-4c02-a657-b7fee94fa8fb)

Make sure you're actually using the reobfJar.
