### ISSUE TITLE
Command finished with 128 exit code

### ISSUE THREAD

**Issue by vortexthedev** [PaperMC/paperweight#202]
> Task :paper:mergeGeneratedAts UP-TO-DATE
> Task :paper:mergeAdditionalAts UP-TO-DATE
> Task :paper:applyMergedAt UP-TO-DATE
> Task :paper:copyResources UP-TO-DATE
> Task :paper:decompileJar UP-TO-DATE
> Task :paper:downloadMcLibrariesSources UP-TO-DATE
> Task :paper:applyServerPatches FAILED
> Task :getPaperUpstreamData FAILED
2 actionable tasks: 2 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':paper:applyServerPatches'.
> io.papermc.paperweight.PaperweightException: Command finished with 128 exit code: git -c commit.gpgsign=false -c core.safecrlf=false reset --hard upstream/master

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
2:07:18: Execution finished 'applyPatches'.

**Comment by Machine-Maker** [comment]
Can you run the task with `-Dpaperweight.debug=true` set and then pastebin the full log output?

**Comment by MiniDigger** [comment]
please join our discord for support

**Comment by vortexthedev** [comment]
I am sorry, but I don't know why I'm banned from PaperMC discord. My discord: vortex#2252 427505684230307850
