### ISSUE TITLE
Support for getDeclaredField and Class#forName in reobfJar

### ISSUE THREAD

**Issue by PlayerSchark** [PaperMC/paperweight#207]
Due to some nested classes in NMS are package-private it should be possible that `Class#forName` and `Class#getDeclaredField` are supported by the reobfJar task.

Example:

`Class.forName("net.minecraft.network.ConnectionProtocol$PacketSet").getDeclaredField("classToId")`
should be reobfuscated to:
`Class.forName("net.minecraft.network.EnumProtocol$a").getDeclaredField("b")`

or:

`Entity.class.getDeclaredField("tickCount")`
should be reobfuscated to:
`Entity.class.getDeclaredField("ag")`

It seems that SpecialSource already supports it in its [RemapperProcessor](https://github.com/md-5/SpecialSource/blob/master/src/main/java/net/md_5/specialsource/RemapperProcessor.java).

**Comment by electronicboy** [comment]
It's worth noting that there are already libraries to handle this at runtime, https://github.com/jpenilla/reflection-remapper

I'm not sure if this is something we will bother with, given our intent to move away from relying on remapping in the future

**Comment by MiniDigger** [comment]
we are in the process of building out tooling for the other direction, obf reflection calls -> mojang mapped source, since paper will ship mojang mapped jars per default in the future, so I dont see this being added to paperweight-userdev
