### ISSUE TITLE
Task 'prepareForDownstream' not found in project ':paper'.

### ISSUE THREAD

**Issue by Toffikk** [PaperMC/paperweight#21]
After updating `paperCommit` in `gradle.properties` to this [commit](https://github.com/PaperMC/Paper/commit/8236add8cbecad5d7a5d87c1db1038523c39da7a)

the build fails with this error message, when running `gradlew applyPatches`

![image](https://user-images.githubusercontent.com/62406295/122387375-1674b980-cf6f-11eb-8c92-53304dc0c2cf.png)

**Comment by mechoriet** [comment]
this seems to happen after https://github.com/PaperMC/Paper/commit/f87d5ab52b3020adad4c909df1211b1d8a862c08

if you paperRef/paperCommit to https://github.com/PaperMC/Paper/commit/52287ea614add9792a791eef9e91b220e29f8499
it applies cleanly

tested this on paperweight-examples as a clean base and on a more modified version that was been updated to latest paperweight patcher
