### ISSUE TITLE
paper fork: Can't run `runDev` task

### ISSUE THREAD

**Issue by s-yh-china** [PaperMC/paperweight#211]
updating `paperweight.patcher` to `1.5.7-SNAPSHOT` and running `runDev`, it will throw
```java
java.lang.NoSuchMethodError: 'void net.minecraft.server.Main.main(joptsimple.OptionSet)'
	at org.bukkit.craftbukkit.Main.main(Main.java:332)
```

but it actually can running in `createReobfPaperclipJar`'s jar

**Comment by granny** [comment]
<img alt="womm" title="Works on my Machine" src="https://github.com/PaperMC/paperweight/assets/43185817/3b16d7f9-9b1f-4a45-a435-7303b90dcd49" width="50" />

No issues for me. I'm assuming you're talking about your Leaves fork - I've gone ahead and cloned it, ran `./gradlew applyPatches`, then `./gradlew runDev` and it also worked fine. More info is needed.

**Comment by s-yh-china** [comment]
i will check it later XD



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 24, 2023 18:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaperMC/paperweight] paper fork: Can't run `runDev` task (Issue #211)




  
No issues for me. I'm assuming you're talking about your Leaves fork - I've gone ahead and cloned it, ran ./gradlew applyPatches, then ./gradlew runDev and it also worked fine. More info is needed.

**Comment by LemonCaramel** [comment]
I have the same issue _(in Paper original repository)_
but the `runReobf` task runs without this issue.
and this issue only occurred on Windows. (not on macOS)

**Comment by s-yh-china** [comment]
is a bug with Paper, not paperweight

**Comment by notTamion** [comment]
> is a bug with Paper, not paperweight

Where you able to fix this? If yes how? I am having the same issue

**Comment by MiniDigger** [comment]
https://github.com/PaperMC/Paper/pull/9797
