### ISSUE TITLE
Paperweight can't remap class if it extends non-included third-party class which extends NMS class

### ISSUE THREAD

**Issue by TheSirCororo** [PaperMC/paperweight#230]
I have 2 classes. One of them is located in jar `A` in module `A` of root project, other located in jar `B` in module `B` of root project. All of them has active paperweight plugin. Module `A` has dependency on module `B` by `compileOnly` (which don't includes it into fat jar).
Module `A` has `AEntity` class which extends `BEntity` in `B` module which extends `PathfinderMob` from NMS.

I have following code:
```java
AEntity a = ...;
GoalSelector goalSelector = a.goalSelector;
```

Bytecode of reobf jar:
```java
AEntity a = ...;
PathfinderGoalSelector goalSelector = a.goalSelector;
```
goalSelector field was NOT remapped.

Core has correct remapped bytecode, but plugin does NOT.

I fixed this by doing following:
```java
AEntity a = ...;
GoalSelector goalSelector = ((PathfinderMob) a).goalSelector;
```

Which was correctly remapped to:
```java
AEntity a = ...;
PathfinderGoalSelector goalSelector = ((EntityCreature) a).oB;
```

Problem occured because paperweight can not detect NMS in other jar (other module) of project.

Possible solution: mark nms classes which remapped by paperweight with metadata and detect it. (maybe annotation processor can be used)

**Comment by jpenilla** [comment]
You need to add the dependency to the remap classpath: https://github.com/PaperMC/paperweight/blob/f1548964e70968eaf360c07c65acea471e3f5cc5/paperweight-lib/src/main/kotlin/io/papermc/paperweight/tasks/RemapJar.kt#L55

**Comment by TheSirCororo** [comment]
What should I provide to this property? I tried to use `from(project(":B").compilations.getByName("compileClasspath")` and runtimeClasspath too but got error or non-changed bytecode. I tried to use `from(project(":B").file("src/main/kotlin")` and it dont work too. Help please.

**Comment by TheSirCororo** [comment]
I fixed it, thanks
