### ISSUE TITLE
spigot transitive deps aren't included in RemapSources which causes mercury remap to fail

### ISSUE THREAD

**Issue by Machine-Maker** [PaperMC/paperweight#232]
Upstream changed from depending on `asm` to `asm-commons` which meant the `asm` sources jar wasn't passed to mercury or eclipse causing it to fail.

**Comment by MiniDigger** [comment]
my suggestion is moving this list to the paperweight or paper extension and then appending the asm dep there 
https://github.com/PaperMC/paperweight/blob/main/paperweight-lib/src/main/kotlin/io/papermc/paperweight/tasks/download-task.kt#L215-L229
