### ISSUE TITLE
Renaming result jar

### ISSUE THREAD

**Issue by DeeChael** [PaperMC/paperweight#234]
Is there any option for reobfJar task like archiveClassifier in shadow plugin?
I want to change the dev suffix.

Or if is there any way to make shadowJar shade the reobfJar jar FROM ANOTHER MODULE because I wanna shade the reobf jar from another module (All under one same parent module)

**Comment by electronicboy** [comment]
The nature of your OR question is suspect that you're wanting to change the dev suffix for the wrong reason, we do not generlly recommend messing with the classifiers as it generally won't solve anything

if you want to consume the reobfuscated jar from another module, then you would specify the "reobf" configuration in the project() declaration

**Comment by DeeChael** [comment]
> The nature of your OR question is suspect that you're wanting to change the dev suffix for the wrong reason, we do not generlly recommend messing with the classifiers as it generally won't solve anything
> 
> if you want to consume the reobfuscated jar from another module, then you would specify the "reobf" configuration in the project() declaration

done, thanks
