### ISSUE TITLE
Code generation does not work in forks because `extractFromBundler` task is not present / registered

### ISSUE THREAD

**Issue by yannicklamprecht** [PaperMC/paperweight#242]
As a fork maintainer I want to use code generation myself to provide API which keys are based on generation from nms classes.

Due to the change here https://github.com/PaperMC/paperweight/commit/c6d776d6f4e2f616f790281d2ef735d5030cab6e#diff-db7b98835ceaf75182242f6aca97b05be8942d5dc4ab0606892ddc3d89f9e684R45 the generation task requires the task `extractFromBundler` to be present. In the current paperweight version this task is only registered in the paperweight spigot decompiling tasks.

Before that the setup with the SpongePowered VanillaGradle work well for forks.

If you need a fork that utilizes api-generator and especially server-generator in both 1.20.4 and 1.20.5 to test your change, let me know.

**Comment by jpenilla** [comment]
Confirmed fixed in v2
