### ISSUE TITLE
[userdev] Changing JDK doesn't invalidate decompile cache

### ISSUE THREAD

**Issue by WillFP** [PaperMC/paperweight#247]
Issue came around when updating from JDK17 to JDK21, the decompilation would fail with cryptic error messages unless the paperweight userdev cache was deleted

**Comment by DarkArc** [comment]
Bumped into this as well (thanks for opening the issue ... I was able to fix it after seeing this by clearing the gradle cache, i.e., `rm -rf $HOME/.gradle/caches/` that particular command is probably a bit heavy handed though)
