### ISSUE TITLE
fork applyPatches repatches paper everytime without any change to paperRef

### ISSUE THREAD

**Issue by mechoriet** [PaperMC/paperweight#25]
It feels a bit redundant to repatches paper repo every time
someone does applyPatches on there fork

like it goes from 
applyApiPatches -> applyServerPatches `-> paper:Paper-API:compileJava -> :paper:Paper-API:jar -> :paper:Paper-MojangAPI:compileJava -> :paper:Paper-Server:compileJava -> :paper:Paper-Server:processResources -> 
:paper:Paper-Server:shadowJar -> :paper:generateReobfMappings` -> applyApiPatches(fork) -> applyServerPatches(fork)

I feel that the steps in the code annotation feel a bit useless for a fork to run if the fork just copies over the repo after it has finished patches.
or there is a specific reasoning for doing all the extra tasks to ensure that upstream is valid/or those files are needed for the fork?

possible suggestion some kind of status file to Ref check gradle.properties to a file that hold current Ref used or check against the paper repo latest commit if the paper upstream repo needs pulling or not or rebuilding cause something has changed

Cause it feels a bit waste of time to reapply all not changing paper patches everytime a fork does a `applyPatches`

**Comment by Toffikk** [comment]
The applyPatches task could be seperated into two tasks `setupUpstream` and `applyPatches`

the setupUpstream task would patch the upstream and applyPatches task would just apply the fork’s patches

**Comment by DenWav** [comment]
originally this cached, and I disabled it because I wanted patches to apply any time the task was run. But you're right, that isn't good for forks.

Instead I think the _current project's_ patch tasks should always run, while upstream patch tasks should cache. I think I can make this work.

**Comment by DenWav** [comment]
Those tasks do need to run, but re-enabling caching correctly will solve the issue.

As for `generateReobfMappings` - I need to move this around a bit. This task should run on the fork project, not the upstream project. Once I fix that, the `shadowJar` and comile tasks will no longer run on upstreams.
