### ISSUE TITLE
Missing classes in server compilation whilst running patcher

### ISSUE THREAD

**Issue by TreemanKing** [PaperMC/paperweight#253]
Version: 1.7.2 Paperweight Patcher

Just a basic paperweight fork project is missing specific classes when compiled using non-reobfuscated compiled jar servers. 

I've tested this with a test plugin that checks for a certain class, in this case `org.bukkit.craftbukkit.block.data.CraftBlockData`.

```java
try {
    Class.forName("org.bukkit.craftbukkit.block.data.CraftBlockData");
    getLogger().info("Class found");
} catch (ClassNotFoundException e) {
    getLogger().severe("Class not found");
}
 ```     
        
However, using non-reobfs, it works fine and a ClassNotFoundException doesn't occur.

Some things I've tried:
- made sure that the build, settings is basically a replica of the paperweight-test-examples and updated to most recent upstream depenencies
- added some paper build things that aren't in the test-examples
```kotlin
reobfPackagesToFix.addAll(
    "com.aikar.timings",
    "com.destroystokyo.paper",
    "com.mojang",
    "io.papermc.paper",
    "ca.spottedleaf",
    "net.kyori.adventure.bossbar",
    "net.minecraft",
    "org.bukkit.craftbukkit",
    "org.spigotmc"
)
```

I've also asked on the paper discord in both `build-tooling-help` and `paper-help` but I was met with no replies.

**Comment by jpenilla** [comment]
Please open a new issue if this is still a problem in v2
