### ISSUE TITLE
`vanilla` isn't a good name for the sourceset for patched files

### ISSUE THREAD

**Issue by Machine-Maker** [PaperMC/paperweight#266]
There are a lot more than just vanilla files inside the `vanilla` sourceset. It's really where all the diff that was patches gets applied, vanilla perfiles but also new file created by the feature patches. Some name that describes its true nature, like `patched` makes more sense.

**Comment by jpenilla** [comment]
`patched` is too generic and would be super confusing for forks, `minecraft` makes more sense than `patched` or `vanilla` imo
