### ISSUE TITLE
Add a functionality to cleanup project

### ISSUE THREAD

**Issue by yannicklamprecht** [PaperMC/paperweight#27]
Currently there is no paperweight task to cleanup / delete api and server output dir.
Once these folders are in a cursed state, applyPatches fails.

```
❯ ./gradlew applyPatches

> Configure project :Some-Server
e: ~/Some-Fork/Some-Server/build.gradle.kts:83:24: Unresolved reference: reobfJar
e: ~/Some-Fork/Some-Server/build.gradle.kts:146:21: Unresolved reference: reobfJar
e: ~/Some-Fork/Some-Server/build.gradle.kts:146:40: Unresolved reference: it

FAILURE: Build failed with an exception.

* Where:
Build file '~/Some-Fork/Some-Server/build.gradle.kts' line: 83

* What went wrong:
Script compilation errors:

  Line 083:         artifact(tasks.reobfJar) {
                                   ^ Unresolved reference: reobfJar

  Line 146:     classpath(tasks.reobfJar.flatMap { it.outputJar })
                                ^ Unresolved reference: reobfJar

  Line 146:     classpath(tasks.reobfJar.flatMap { it.outputJar })
                                                   ^ Unresolved reference: it

3 errors
```

**Comment by Proximyst** [comment]
I hardly think `rm -rf Paper-{API,Server}` qualifies as a Gradle task necessity.

**Comment by yannicklamprecht** [comment]
> I hardly think `rm -rf Paper-{API,Server}` qualifies as a Gradle task necessity.

It's just convenient to have one.

**Comment by DenWav** [comment]
The problem is Gradle tasks can't run if the sub-projects are broken due to the configuration step failing (this happens pre-task execution).

we are going to bring back the `paper` script soon to help bridge the gap between the old system and the new, and provide helper scripts which aren't feasible in Gradle - this command can be included in that script.
