### ISSUE TITLE
Error: Expected configuration ':paperweightDevelopmentBundle' to contain exactly one file, however, it contains more than one file.

### ISSUE THREAD

**Issue by Jufyer** [PaperMC/paperweight#273]
When I change the dependency from: 

`dependencies {
  paperweight.paperDevBundle("1.21.1-R0.1-SNAPSHOT")
}`

to: 

`dependencies {
  paperweight.paperDevBundle("1.21.4-R0.1-SNAPSHOT")
}`

I get the error from the title. Can I do something about this?

**Comment by jpenilla** [comment]
https://github.com/PaperMC/paperweight/issues/272
