### ISSUE TITLE
Reflection Mappings

### ISSUE THREAD

**Issue by Owen1212055** [PaperMC/paperweight#35]
Most likely a long term goal (userdev), but would be an incredible convenience for plugins using (although unsupported) reflection on NMS. 

https://discord.com/channels/289587909051416579/555462289851940864/856007221217460234

**Comment by DenWav** [comment]
This isn't impossible but it's also not easy. Would only be able to ever handle very simple cases, and static cases. Any time you're using a non-static string for the name it's not going to be possible.

**Comment by Owen1212055** [comment]
I think
https://github.com/jpenilla/reflection-remapper

is most likely the best thing to use in this case instead.
