### ISSUE TITLE
reobf-mappings-patch.tiny uses wrong mapping namespace

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/paperweight#36]
https://github.com/PaperMC/paperweight/blob/main/paperweight-lib/src/main/kotlin/tasks/PatchMappings.kt#L79

"It's hard coded, needs to be made into task inputs"

**Comment by DenWav** [comment]
Fixed in https://github.com/PaperMC/paperweight/commit/e0ac40d687f993db3b0e8a2549d0e19200cd55ec.
