### ISSUE TITLE
Fork: a way to do similar function as upstreamCommit.sh

### ISSUE THREAD

**Issue by mechoriet** [PaperMC/paperweight#37]
A way for forks running Paperweight to create a commit with the upstream changes,
so they also know what commits,
got pulled in since there last upstream Ref change similar to this like Paper's *bukkit/craftbukkit/spigot* upstream commits
https://github.com/PaperMC/Paper/commit/17f71ac87b7967ba203d34f039563a31010f26af

**Comment by TheKinrar** [comment]
I guess you could use submodules and re-use the legacy script for that, seems like this is what Paper is doing. https://github.com/PaperMC/Paper/blob/47605b8e6035260be98c8650a736306a0a39258d/scripts/upstreamCommit.sh

**Comment by electronicboy** [comment]
Pretty sure that this is all just done using those same scripts still? Just copy them into your repo.

**Comment by mechoriet** [comment]
> Pretty sure that this is all just done using those same scripts still? Just copy them into your repo.

I understand that paper it self does that with there work/{bukkit,craftbukkit,spigot}

but how would forks that use the default system(PaperRef) be able to do that? 
where the repo gets pulled with depth of 1 which is little to none history information

or is that something that would require the usage submodules?

**Comment by DenWav** [comment]
Will need to figure out what this would look like.

**Comment by DenWav** [comment]
This should just be handled in a script like in PaperMC/Paper#6009.

Would only require a slight modification to the script to properly support. When I get to it I'll put modified versions of the script in https://github.com/PaperMC/paperweight-examples
