### ISSUE TITLE
Fork: PaperRef change not detected when running applyPatches

### ISSUE THREAD

**Issue by mechoriet** [PaperMC/paperweight#39]
I feel this mechanic of the system got broken or got changed with issue: #25 
`note: this was using the useStandardUpstream type` which could have been a bit different in behavior but they look the same in working

- [ ] check if this also happens on a blank Paper Fork repo

Maybe there is a way to match PaperRef to cached paper repo,
If HEAD = PaperRef commit hash else 
Re-pull and rerun all the steps that normally get bypassed due to changed made #25

or was this intentional and someone should run cleanCache before applyPatches?

**Comment by DenWav** [comment]
Please provide a link to your repo - nothing to go off of here currently.

**Comment by mechoriet** [comment]
tried it on a fresh paperweight-example then changed to useStandardUpstream to base of tuinity,
and then took a older commit Ref then changed to latest.
it got detected on applyPatches maybe I just borked something,
or some desync somewhere from wsl2
