### ISSUE TITLE
Detect upstream changes to pom

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/paperweight#4]
as raised by aikar in https://github.com/PaperMC/Paper/issues/1026

**Comment by DemonWav** [comment]
I'm not 100% convinced this is needed. Pom changes in Spigot would mean the patch that concerts the project to Gradle would fail. So it's sort of just built into it already by the nature of patches.

**Comment by DemonWav** [comment]
Closing due to previous comment.
