### ISSUE TITLE
Run Server Task

### ISSUE THREAD

**Issue by underscore11code** [PaperMC/paperweight#41]
Pretty simple, add a task that builds a new paperclip and then runs it (in a directory more sensible than `build/libs`).

**Comment by underscore11code** [comment]
I'm such an absolute moron, this already exists (`runDev`). _11 = PEBKAC confirmed.

**Comment by MiniDigger** [comment]
runDev = runs from source
runShadow = builds shadowjar and runs that
runReobf = builds shadow jar, reobfuscates it and runs that
