### ISSUE TITLE
Provide a Mod Development Kit (MDK)

### ISSUE THREAD

**Issue by DarkArc** [PaperMC/paperweight#42]
This is a tracking issue per [this brief discussion](https://discord.com/channels/289587909051416579/555462289851940864/855909591741497405) for the MDK.

Notable items:
- [ ] Implement a MDK gradle plugin (?) to allow easily developing mods against mojang mappings, then building the mod with runtime mappings
- [ ] Document the usage of said MDK

**Comment by DenWav** [comment]
#47
