### ISSUE TITLE
Rebuild patches task sends all paper commits to the patches folder

### ISSUE THREAD

**Issue by KorkugunuB** [PaperMC/paperweight#46]
Rebuild patches task sends all paper commits to the patches folder
I just want my commits to come. but the upstream commits are coming, too.

build.gradle.kts: https://hastebin.com/efejamubeb.kotlin
gradle.properties: https://hastebin.com/foyamaqofa.properties
settings.gradle.kts: https://hastebin.com/xosudizego.kotlin

server patches folder: https://imgur.com/XOIBF7H

**Comment by Toffikk** [comment]
I can’t reproduce this
