### ISSUE TITLE
Project doesn't compile

### ISSUE THREAD

**Issue by BigBadE** [PaperMC/paperweight#6]
Three problems:
1. The repo "https://repo.demonwav.com/snapshots/" dependency "org.cadixdev:mercury:0.1.0-rc2-SNAPSHOT" throws a 502, erroring the build
Since @DemonWav seems to be the main contributor, this is probably just their repo server going down.
2. GenerateMappings line 80 throws a resolution ambiguity error
simple enough fix, cast null to a classloader
3. Doesn't provide a plugin with the right id
Full error:

* What went wrong:
Could not apply requested plugin [id: 'io.papermc.paperweight', version: '1.0.0-LOCAL-SNAPSHOT'] as it does not provide a plugin with id 'io.papermc.paperweight'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'io.papermc.paperweight' not found.

**Comment by BigBadE** [comment]
Why was this closed?

**Comment by DemonWav** [comment]
This is not ready for you to use yet.
