### ISSUE TITLE
Rework dev bundle patch generation to not use GNU diff

### ISSUE THREAD

**Issue by jpenilla** [PaperMC/paperweight#65]
This is generally not very high priority as most of the time dev bundles will be generated by CI and published to maven, but it would be nice to not need GNU diff for dev bundle generation, for easier local testing on macOS (for those who for some reason don't install GNU coreutils) and Windows.

Two possible alternatives are
- Using git to generate the patches (looked into briefly before and didn't have much luck, but I was probably missing something obvious)
- Using Diff4j/Diffpatch/something else to generate the patches

**Comment by rgnter** [comment]
[GNU DiffUtils ](http://gnuwin32.sourceforge.net/packages/diffutils.htm) does not have `--color` option. This should be marked as bug, not an "enhancement".

**Comment by MiniDigger** [comment]
> [GNU DiffUtils ](http://gnuwin32.sourceforge.net/packages/diffutils.htm) does not have `--color` option. This should be marked as bug, not an "enhancement".

thats wrong https://www.gnu.org/software/diffutils/manual/diffutils.html#index-color_002c-distinguishing-different-context

**Comment by rgnter** [comment]
It's not available in prebuilt version 2.8.

**Comment by NotMyFault** [comment]
In 10 days, 2.8 celebrates 20th anniversary. --color was originally introduced in 3.4, but you should update to the newest release from a few months ago; 3.8.
However, I'm currently on 3.7 and it works out of the box as well.

**Comment by rgnter** [comment]
It's not available standalone, after installing pacman I finally managed to get it.
