### ISSUE TITLE
Attach minecraft sources to intellij

### ISSUE THREAD

**Issue by Machine-Maker** [PaperMC/paperweight#9]
https://github.com/PaperMC/Paper/blob/master/scripts/makemcdevsrc.sh

Useful for adding a new content route for all files that werent already imported. Makes navigating around the source much easier in various IDEs

**Comment by DenWav** [comment]
I want to improve this in paperweight so it just happens automatically, though I know VanillaGradle had a lot of issues attaching sources. @zml2008

**Comment by zml2008** [comment]
Yeah, the only way I was able to make source attaching work 'automatically' was to expose MC as an artifact in a local ivy repository, generated on resolution. My decompile task creates an artifact in that repository with a `sources` classifier.

Some scribbles about VG's current architecture are documented on [the wiki](https://github.com/SpongePowered/VanillaGradle/wiki/Implementation-Details#gradle-hooks)
